# Enable split keyboard support
CONFIG_ZMK_SPLIT=y

# Enable display
CONFIG_ZMK_DISPLAY=y

# Enable display work queue
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable pointing/mouse subsystem
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
